[package]
name = "vs-tui"
version = "0.1.0"
description = "vscode alternative in your cli"
authors = ["valmnt <valentinmont8@gmail.com>"]
license = "MIT"
edition = "2024"

[dependencies]
crossterm = "0.28.1"
ratatui = "0.29.0"
color-eyre = "0.6.3"
